<a href="https://colab.research.google.com/github/Gladiator07/Natural-Language-Processing/blob/main/RNN/RNN-from-scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## RNN from scratch in PyTorch

![](https://miro.medium.com/max/840/1*o65pRKyHxhw7m8LgMbVERg.png)

First, let’s build the computation graph for a single-layer RNN. Again, we are not concerned with the math for now, I just want to show you the PyTorch operations needed to build your RNN models.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import os
import numpy as np

In [2]:
class SingleRNN(nn.Module):
    def __init__(self, n_inputs, n_neurons):
        super(SingleRNN, self).__init__()

        self.Wx = torch.randn(n_inputs, n_neurons)  # 4 x 1
        self.Wy = torch.randn(n_neurons, n_neurons) # 1 x 1

        self.b = torch.zeros(1, n_neurons) # 1 x 4
    
    def forward(self, X0, X1):
        self.Y0 = torch.tanh(torch.mm(X0, self.Wx) + self.b) # 4 x 1

        self.Y1 = torch.tanh(torch.mm(self.Y0, self.Wy) + 
                             torch.mm(X1, self.Wx) + self.b) # 4 x 1
        
        return self.Y0, self.Y1

The forward function computes two outputs — one for each time step (two overall). Note that we are using tanh as the non-linearity (activation function) via torch.tanh(...).

This is how the data is fed into RNN:

![](https://miro.medium.com/max/764/1*xCj9h3f2kekfqN_dMCpcag.png)

In [3]:
N_INPUT = 4
N_NEURONS = 1


X0_batch = torch.tensor([[0,1,2,0], [3,4,5,0], 
                         [6,7,8,0], [9,0,1,0]],
                        dtype = torch.float) #t=0 => 4 X 4

X1_batch = torch.tensor([[9,8,7,0], [0,0,0,0], 
                         [6,5,4,0], [3,2,1,0]],
                        dtype = torch.float) #t=1 => 4 X 4
model = SingleRNN(N_INPUT, N_NEURONS)

Y0_val, Y1_val = model(X0_batch, X1_batch)

In [4]:
print(Y0_val)
print(Y1_val)

tensor([[-0.9544],
        [-0.0408],
        [ 0.9465],
        [ 1.0000]])
tensor([[1.0000],
        [0.0377],
        [0.9998],
        [0.9925]])


### Increasing neurons in RNN Layer

![](https://miro.medium.com/max/840/1*KLBXIeszx_cqkYs3-EXHwg.png)

In [5]:
class BasicRNN(nn.Module):
    def __init__(self, n_inputs, n_neurons):
        super(BasicRNN, self).__init__()

        self.Wx = torch.randn(n_inputs, n_neurons) # n_inputs x n_neurons
        self.Wy = torch.randn(n_neurons, n_neurons) # n_neurons x n_neurons

        self.b = torch.zeros(1, n_neurons) # 1 x neurons

    def forward(self, X0, X1):
        self.Y0 = torch.tanh(torch.mm(X0, self.Wx) + self.b) # batch_size x n_neurons
        self.Y1 = torch.tanh(torch.mm(self.Y0, self.Wy) + torch.mm(X1, self.Wx) + self.b) # batch_size x n_neurons

        return self.Y0, self.Y1    

In [6]:
N_INPUT = 3 # number of features in input
N_NEURONS = 5 # number of units in layer

X0_batch = torch.tensor([[0,1,2], [3,4,5], 
                         [6,7,8], [9,0,1]],
                        dtype = torch.float) #t=0 => 4 X 3

X1_batch = torch.tensor([[9,8,7], [0,0,0], 
                         [6,5,4], [3,2,1]],
                        dtype = torch.float) #t=1 => 4 X 3

model = BasicRNN(N_INPUT, N_NEURONS)

Y0_val, Y1_val = model(X0_batch, X1_batch)

In [7]:
print(Y0_val)
print(Y1_val)

tensor([[-0.4270, -0.2270,  0.1532, -0.5908,  0.9927],
        [-0.8519, -0.8407,  1.0000, -1.0000, -0.9086],
        [-0.9686, -0.9765,  1.0000, -1.0000, -1.0000],
        [ 0.9845, -0.4702,  1.0000, -1.0000, -1.0000]])
tensor([[-0.8298, -0.9995,  1.0000, -1.0000, -1.0000],
        [-0.7453,  0.9513,  0.6089,  0.1575, -0.8982],
        [-0.9818,  0.1597,  1.0000, -1.0000, -1.0000],
        [-0.7212,  0.9855,  1.0000, -1.0000, -1.0000]])
